import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * Scan Result Card Component
 * Displays GitHub profile scan in short form with expandable details
 */
import React from 'react';
import { formatDistanceToNow } from 'date-fns';
export default function ScanResultCard({ id, username, github_user_id, repoCount, contributionStats, lastScannedAt, onViewDetails, isGuest = false, profileImage, }) {
    const scannedTime = new Date(lastScannedAt);
    const timeAgo = formatDistanceToNow(scannedTime, { addSuffix: true });
    return (_jsxs("div", { className: "bg-white rounded-lg border border-gray-200 p-5 hover:shadow-md transition-shadow", children: [_jsxs("div", { className: "flex items-start justify-between mb-4", children: [_jsxs("div", { className: "flex items-start gap-3 flex-1", children: [profileImage && (_jsx("img", { src: profileImage, alt: username, className: "w-12 h-12 rounded-full" })), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("a", { href: `https://github.com/${username}`, target: "_blank", rel: "noopener noreferrer", className: "text-lg font-semibold text-blue-600 hover:text-blue-700 truncate", children: username }), isGuest && (_jsx("span", { className: "inline-block bg-yellow-100 text-yellow-800 text-xs font-semibold px-2.5 py-0.5 rounded", children: "Guest" }))] }), _jsxs("p", { className: "text-sm text-gray-500 mt-1", children: ["Scanned ", timeAgo] })] })] }), _jsx("button", { onClick: onViewDetails, className: "ml-2 px-3 py-1 bg-blue-50 text-blue-600 hover:bg-blue-100 rounded text-sm font-medium transition-colors", children: "View" })] }), contributionStats && (_jsxs("div", { className: "grid grid-cols-3 gap-3 mb-4", children: [_jsxs("div", { className: "bg-blue-50 rounded p-3", children: [_jsx("p", { className: "text-xs text-gray-600 font-medium", children: "Commits" }), _jsx("p", { className: "text-xl font-bold text-blue-600", children: contributionStats.commits.toLocaleString() })] }), _jsxs("div", { className: "bg-purple-50 rounded p-3", children: [_jsx("p", { className: "text-xs text-gray-600 font-medium", children: "Pull Requests" }), _jsx("p", { className: "text-xl font-bold text-purple-600", children: contributionStats.pullRequests.toLocaleString() })] }), _jsxs("div", { className: "bg-green-50 rounded p-3", children: [_jsx("p", { className: "text-xs text-gray-600 font-medium", children: "Issues" }), _jsx("p", { className: "text-xl font-bold text-green-600", children: contributionStats.issues.toLocaleString() })] })] })), _jsxs("div", { className: "flex items-center justify-between text-sm text-gray-600 border-t pt-3", children: [_jsxs("span", { children: ["\uD83D\uDCE6 ", repoCount, " Repositories"] }), _jsxs("span", { className: "text-xs text-gray-400", children: ["ID: ", github_user_id.slice(0, 8), "..."] })] })] }));
}
