"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { X } from "lucide-react";
import Link from "next/link";
export default function UpgradeModal({ isOpen, onClose, feature = "this feature", currentPlan = "current", }) {
    if (!isOpen)
        return null;
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm", children: _jsxs("div", { className: "bg-linear-to-br from-gray-900 to-purple-900 border-2 border-purple-500 rounded-2xl p-8 max-w-md w-full mx-4 relative", children: [_jsx("button", { onClick: onClose, className: "absolute top-4 right-4 text-gray-400 hover:text-white transition-colors", children: _jsx(X, { size: 24 }) }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-6xl mb-4", children: "\uD83D\uDE80" }), _jsx("h2", { className: "text-3xl font-bold text-white mb-4", children: "Upgrade Required" }), _jsxs("p", { className: "text-gray-300 mb-6", children: ["You've reached the limit for ", _jsx("span", { className: "text-purple-400 font-semibold", children: feature }), " on the", " ", _jsx("span", { className: "font-semibold", children: currentPlan }), " plan."] }), _jsxs("div", { className: "bg-white/10 rounded-lg p-4 mb-6", children: [_jsx("p", { className: "text-sm text-gray-200 mb-2", children: "Upgrade to unlock:" }), _jsxs("ul", { className: "text-left text-sm space-y-2 text-gray-300", children: [_jsx("li", { children: "\u2713 Unlimited scans" }), _jsx("li", { children: "\u2713 Bug detection & security scanning" }), _jsx("li", { children: "\u2713 Full history access" }), _jsx("li", { children: "\u2713 PR auto-generation" })] })] }), _jsx(Link, { href: "/pricing", children: _jsx("button", { className: "w-full bg-linear-to-r from-purple-500 to-pink-500 text-white py-3 rounded-lg font-semibold hover:shadow-lg hover:shadow-purple-500/50 transition-all duration-300 mb-3", children: "View Pricing Plans" }) }), _jsx("button", { onClick: onClose, className: "w-full bg-white/10 text-white py-2 rounded-lg hover:bg-white/20 transition-colors", children: "Maybe Later" })] })] }) }));
}
