import { Octokit } from 'octokit';

export interface CreateReadmePrInput {
  octokit: Octokit;
  owner: string;
  repo: string;
  readmeContent: string;
  title?: string;
  body?: string;
  branchPrefix?: string;
}

export interface CreateReadmePrResult {
  branchName: string;
  prUrl: string;
  prNumber: number;
}

async function getExistingFileSha(
  octokit: Octokit,
  owner: string,
  repo: string,
  path: string,
  branch: string
): Promise<string | undefined> {
  try {
    const response = await octokit.rest.repos.getContent({ owner, repo, path, ref: branch });
    const data = response.data as { sha?: string } | Array<unknown>;
    if (Array.isArray(data)) return undefined;
    return data?.sha;
  } catch {
    return undefined;
  }
}

export async function createReadmePullRequest(input: CreateReadmePrInput): Promise<CreateReadmePrResult> {
  const {
    octokit,
    owner,
    repo,
    readmeContent,
    title = 'docs: improve README with repository intelligence summary',
    body = 'Automated README update generated by ClarityCode.',
    branchPrefix = 'claritycode/readme',
  } = input;

  const repoInfo = await octokit.rest.repos.get({ owner, repo });
  const baseBranch = repoInfo.data.default_branch;

  const baseRef = await octokit.rest.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
  const baseSha = baseRef.data.object.sha;

  const branchName = `${branchPrefix}-${Date.now()}`;
  await octokit.rest.git.createRef({ owner, repo, ref: `refs/heads/${branchName}`, sha: baseSha });

  const existingSha = await getExistingFileSha(octokit, owner, repo, 'README.md', baseBranch);

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: 'README.md',
    message: title,
    content: Buffer.from(readmeContent, 'utf8').toString('base64'),
    branch: branchName,
    sha: existingSha,
  });

  const pr = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    head: branchName,
    base: baseBranch,
    body,
  });

  return {
    branchName,
    prUrl: pr.data.html_url,
    prNumber: pr.data.number,
  };
}
